project:
  type: website
  output-dir: docs

website:
  title: "Calendários IECOS – 4º Período 2025"
  page-navigation: false

format:
  html:
    theme: flatly
    css: assets/css/cal.css     # só o CSS
    page-layout: full
