project:
  type: website
  output-dir: docs

website:
  title: "Calendários Acadêmicos"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Engenharia de Pesca"
        contents:
          - text: "Turma T2022 - 4º Período"
            href: calendarios/EP_T2022_4P-2025.html
          - text: "Turma T2023 - 4º Período"
            href: calendarios/EP_T2023_4P-2025.html
          - text: "Turma T2024 - 4º Período"
            href: calendarios/EP_T2024_4P-2025.html
          - text: "Turma T2025 - 4º Período"
            href: calendarios/EP_T2025_4P-2025.html
      - section: "Outros Cursos"
        contents:
          - text: "Em breve..."
            href: "#"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right