project:
  type: website
  output-dir: docs

website:
  title: "Calendários IECOS – 4º Período 2025"
  page-navigation: false          # sem navegação automática

format:
  html:
    theme: flatly                  # pode trocar depois
    css: assets/css/custom_calendars.css
    page-layout: full
    include-in-header: |
      <!-- Fonte Google Inter -->
      <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">
