project:
  type: website
  output-dir: docs

website:
  title: "Calendários IECOS – 4º Período 2025"
  page-navigation: false

format:
  html:
    theme: flatly
    css: assets/css/cal.css      # novo css enxuto
    page-layout: full
    include-in-header: |
      <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">
